
task.cancel(true)
task.get() // throws an Exception
